// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: gRPC/gin-study.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Importance int32

const (
	Importance_MEDIUM    Importance = 0
	Importance_VERY_HIGH Importance = 1
	Importance_HIGH      Importance = 2
	Importance_LOW       Importance = 3
)

// Enum value maps for Importance.
var (
	Importance_name = map[int32]string{
		0: "MEDIUM",
		1: "VERY_HIGH",
		2: "HIGH",
		3: "LOW",
	}
	Importance_value = map[string]int32{
		"MEDIUM":    0,
		"VERY_HIGH": 1,
		"HIGH":      2,
		"LOW":       3,
	}
)

func (x Importance) Enum() *Importance {
	p := new(Importance)
	*p = x
	return p
}

func (x Importance) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Importance) Descriptor() protoreflect.EnumDescriptor {
	return file_gRPC_gin_study_proto_enumTypes[0].Descriptor()
}

func (Importance) Type() protoreflect.EnumType {
	return &file_gRPC_gin_study_proto_enumTypes[0]
}

func (x Importance) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Importance.Descriptor instead.
func (Importance) EnumDescriptor() ([]byte, []int) {
	return file_gRPC_gin_study_proto_rawDescGZIP(), []int{0}
}

type TimestampCompareBy int32

const (
	TimestampCompareBy_SAME   TimestampCompareBy = 0
	TimestampCompareBy_BEFORE TimestampCompareBy = 1
	TimestampCompareBy_AFTER  TimestampCompareBy = 2
)

// Enum value maps for TimestampCompareBy.
var (
	TimestampCompareBy_name = map[int32]string{
		0: "SAME",
		1: "BEFORE",
		2: "AFTER",
	}
	TimestampCompareBy_value = map[string]int32{
		"SAME":   0,
		"BEFORE": 1,
		"AFTER":  2,
	}
)

func (x TimestampCompareBy) Enum() *TimestampCompareBy {
	p := new(TimestampCompareBy)
	*p = x
	return p
}

func (x TimestampCompareBy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimestampCompareBy) Descriptor() protoreflect.EnumDescriptor {
	return file_gRPC_gin_study_proto_enumTypes[1].Descriptor()
}

func (TimestampCompareBy) Type() protoreflect.EnumType {
	return &file_gRPC_gin_study_proto_enumTypes[1]
}

func (x TimestampCompareBy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimestampCompareBy.Descriptor instead.
func (TimestampCompareBy) EnumDescriptor() ([]byte, []int) {
	return file_gRPC_gin_study_proto_rawDescGZIP(), []int{1}
}

type CreateTaskRequestParam_Importance int32

const (
	CreateTaskRequestParam_MEDIUM    CreateTaskRequestParam_Importance = 0
	CreateTaskRequestParam_VERY_HIGH CreateTaskRequestParam_Importance = 1
	CreateTaskRequestParam_HIGH      CreateTaskRequestParam_Importance = 2
	CreateTaskRequestParam_LOW       CreateTaskRequestParam_Importance = 3
)

// Enum value maps for CreateTaskRequestParam_Importance.
var (
	CreateTaskRequestParam_Importance_name = map[int32]string{
		0: "MEDIUM",
		1: "VERY_HIGH",
		2: "HIGH",
		3: "LOW",
	}
	CreateTaskRequestParam_Importance_value = map[string]int32{
		"MEDIUM":    0,
		"VERY_HIGH": 1,
		"HIGH":      2,
		"LOW":       3,
	}
)

func (x CreateTaskRequestParam_Importance) Enum() *CreateTaskRequestParam_Importance {
	p := new(CreateTaskRequestParam_Importance)
	*p = x
	return p
}

func (x CreateTaskRequestParam_Importance) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateTaskRequestParam_Importance) Descriptor() protoreflect.EnumDescriptor {
	return file_gRPC_gin_study_proto_enumTypes[2].Descriptor()
}

func (CreateTaskRequestParam_Importance) Type() protoreflect.EnumType {
	return &file_gRPC_gin_study_proto_enumTypes[2]
}

func (x CreateTaskRequestParam_Importance) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateTaskRequestParam_Importance.Descriptor instead.
func (CreateTaskRequestParam_Importance) EnumDescriptor() ([]byte, []int) {
	return file_gRPC_gin_study_proto_rawDescGZIP(), []int{6, 0}
}

type GetMyCatMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetCat string `protobuf:"bytes,1,opt,name=target_cat,json=targetCat,proto3" json:"target_cat,omitempty"`
}

func (x *GetMyCatMessage) Reset() {
	*x = GetMyCatMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gRPC_gin_study_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMyCatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyCatMessage) ProtoMessage() {}

func (x *GetMyCatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_gin_study_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyCatMessage.ProtoReflect.Descriptor instead.
func (*GetMyCatMessage) Descriptor() ([]byte, []int) {
	return file_gRPC_gin_study_proto_rawDescGZIP(), []int{0}
}

func (x *GetMyCatMessage) GetTargetCat() string {
	if x != nil {
		return x.TargetCat
	}
	return ""
}

type MyCatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
}

func (x *MyCatResponse) Reset() {
	*x = MyCatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gRPC_gin_study_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyCatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyCatResponse) ProtoMessage() {}

func (x *MyCatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_gin_study_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyCatResponse.ProtoReflect.Descriptor instead.
func (*MyCatResponse) Descriptor() ([]byte, []int) {
	return file_gRPC_gin_study_proto_rawDescGZIP(), []int{1}
}

func (x *MyCatResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MyCatResponse) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type Task struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Details string `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	// 重要度
	Importance Importance `protobuf:"varint,4,opt,name=importance,proto3,enum=Importance" json:"importance,omitempty"`
	// 登録日時（タイムスタンプ）
	RegisteredAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	// 期限日時（タイムスタンプ）
	Deadline *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=deadline,proto3" json:"deadline,omitempty"`
	// 更新日時（タイムスタンプ）
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Task) Reset() {
	*x = Task{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gRPC_gin_study_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_gin_study_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_gRPC_gin_study_proto_rawDescGZIP(), []int{2}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *Task) GetImportance() Importance {
	if x != nil {
		return x.Importance
	}
	return Importance_MEDIUM
}

func (x *Task) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

func (x *Task) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *Task) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Tasks struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tasks []*Task `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
}

func (x *Tasks) Reset() {
	*x = Tasks{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gRPC_gin_study_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tasks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tasks) ProtoMessage() {}

func (x *Tasks) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_gin_study_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tasks.ProtoReflect.Descriptor instead.
func (*Tasks) Descriptor() ([]byte, []int) {
	return file_gRPC_gin_study_proto_rawDescGZIP(), []int{3}
}

func (x *Tasks) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type GetTaskByIdRequestParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetTaskByIdRequestParam) Reset() {
	*x = GetTaskByIdRequestParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gRPC_gin_study_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTaskByIdRequestParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskByIdRequestParam) ProtoMessage() {}

func (x *GetTaskByIdRequestParam) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_gin_study_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskByIdRequestParam.ProtoReflect.Descriptor instead.
func (*GetTaskByIdRequestParam) Descriptor() ([]byte, []int) {
	return file_gRPC_gin_study_proto_rawDescGZIP(), []int{4}
}

func (x *GetTaskByIdRequestParam) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTaskByConditionRequestParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Details string `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	// 重要度
	Importance Importance `protobuf:"varint,3,opt,name=importance,proto3,enum=Importance" json:"importance,omitempty"`
	// 登録日時（タイムスタンプ）
	RegisteredAt             *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	SerachTypeForRegisterdAt TimestampCompareBy     `protobuf:"varint,5,opt,name=serachTypeForRegisterdAt,proto3,enum=TimestampCompareBy" json:"serachTypeForRegisterdAt,omitempty"`
	// 期限日時（タイムスタンプ）
	Deadline              *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=deadline,proto3" json:"deadline,omitempty"`
	SerachTypeForDeadline TimestampCompareBy     `protobuf:"varint,7,opt,name=serachTypeForDeadline,proto3,enum=TimestampCompareBy" json:"serachTypeForDeadline,omitempty"`
	// 更新日時（タイムスタンプ）
	UpdatedAt              *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SerachTypeForUpdatedAt TimestampCompareBy     `protobuf:"varint,9,opt,name=serachTypeForUpdatedAt,proto3,enum=TimestampCompareBy" json:"serachTypeForUpdatedAt,omitempty"`
}

func (x *GetTaskByConditionRequestParam) Reset() {
	*x = GetTaskByConditionRequestParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gRPC_gin_study_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTaskByConditionRequestParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskByConditionRequestParam) ProtoMessage() {}

func (x *GetTaskByConditionRequestParam) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_gin_study_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskByConditionRequestParam.ProtoReflect.Descriptor instead.
func (*GetTaskByConditionRequestParam) Descriptor() ([]byte, []int) {
	return file_gRPC_gin_study_proto_rawDescGZIP(), []int{5}
}

func (x *GetTaskByConditionRequestParam) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetTaskByConditionRequestParam) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *GetTaskByConditionRequestParam) GetImportance() Importance {
	if x != nil {
		return x.Importance
	}
	return Importance_MEDIUM
}

func (x *GetTaskByConditionRequestParam) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

func (x *GetTaskByConditionRequestParam) GetSerachTypeForRegisterdAt() TimestampCompareBy {
	if x != nil {
		return x.SerachTypeForRegisterdAt
	}
	return TimestampCompareBy_SAME
}

func (x *GetTaskByConditionRequestParam) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *GetTaskByConditionRequestParam) GetSerachTypeForDeadline() TimestampCompareBy {
	if x != nil {
		return x.SerachTypeForDeadline
	}
	return TimestampCompareBy_SAME
}

func (x *GetTaskByConditionRequestParam) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *GetTaskByConditionRequestParam) GetSerachTypeForUpdatedAt() TimestampCompareBy {
	if x != nil {
		return x.SerachTypeForUpdatedAt
	}
	return TimestampCompareBy_SAME
}

type CreateTaskRequestParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Details string `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	// 重要度
	Importance CreateTaskRequestParam_Importance `protobuf:"varint,3,opt,name=importance,proto3,enum=CreateTaskRequestParam_Importance" json:"importance,omitempty"`
	// 期限日時（タイムスタンプ）
	Deadline *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deadline,proto3" json:"deadline,omitempty"`
}

func (x *CreateTaskRequestParam) Reset() {
	*x = CreateTaskRequestParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gRPC_gin_study_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTaskRequestParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequestParam) ProtoMessage() {}

func (x *CreateTaskRequestParam) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_gin_study_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequestParam.ProtoReflect.Descriptor instead.
func (*CreateTaskRequestParam) Descriptor() ([]byte, []int) {
	return file_gRPC_gin_study_proto_rawDescGZIP(), []int{6}
}

func (x *CreateTaskRequestParam) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTaskRequestParam) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *CreateTaskRequestParam) GetImportance() CreateTaskRequestParam_Importance {
	if x != nil {
		return x.Importance
	}
	return CreateTaskRequestParam_MEDIUM
}

func (x *CreateTaskRequestParam) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

type UpdateTaskRequestParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Details string `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	// 重要度
	Importance Importance `protobuf:"varint,4,opt,name=importance,proto3,enum=Importance" json:"importance,omitempty"`
	// 期限日時（タイムスタンプ）
	Deadline *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=deadline,proto3" json:"deadline,omitempty"`
}

func (x *UpdateTaskRequestParam) Reset() {
	*x = UpdateTaskRequestParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gRPC_gin_study_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTaskRequestParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskRequestParam) ProtoMessage() {}

func (x *UpdateTaskRequestParam) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_gin_study_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskRequestParam.ProtoReflect.Descriptor instead.
func (*UpdateTaskRequestParam) Descriptor() ([]byte, []int) {
	return file_gRPC_gin_study_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTaskRequestParam) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTaskRequestParam) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTaskRequestParam) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *UpdateTaskRequestParam) GetImportance() Importance {
	if x != nil {
		return x.Importance
	}
	return Importance_MEDIUM
}

func (x *UpdateTaskRequestParam) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

type DeleteTaskRequestParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteTaskRequestParam) Reset() {
	*x = DeleteTaskRequestParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gRPC_gin_study_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTaskRequestParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequestParam) ProtoMessage() {}

func (x *DeleteTaskRequestParam) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_gin_study_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequestParam.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequestParam) Descriptor() ([]byte, []int) {
	return file_gRPC_gin_study_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteTaskRequestParam) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_gRPC_gin_study_proto protoreflect.FileDescriptor

var file_gRPC_gin_study_proto_rawDesc = []byte{
	0x0a, 0x14, 0x67, 0x52, 0x50, 0x43, 0x2f, 0x67, 0x69, 0x6e, 0x2d, 0x73, 0x74, 0x75, 0x64, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x30, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4d, 0x79, 0x43, 0x61, 0x74,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x5f, 0x63, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x43, 0x61, 0x74, 0x22, 0x37, 0x0a, 0x0d, 0x4d, 0x79, 0x43, 0x61, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b,
	0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x22,
	0xa5, 0x02, 0x0a, 0x04, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x2b, 0x0a, 0x0a, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x49, 0x6d, 0x70,
	0x6f, 0x72, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x0a, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x12, 0x3f, 0x0a, 0x0d, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0c, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x36, 0x0a, 0x08, 0x64, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x08, 0x64, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x39, 0x0a, 0x0a,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x24, 0x0a, 0x05, 0x54, 0x61, 0x73, 0x6b, 0x73,
	0x12, 0x1b, 0x0a, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x05, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x22, 0x29, 0x0a,
	0x17, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x98, 0x04, 0x0a, 0x1e, 0x47, 0x65, 0x74,
	0x54, 0x61, 0x73, 0x6b, 0x42, 0x79, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x2b, 0x0a, 0x0a, 0x69, 0x6d, 0x70,
	0x6f, 0x72, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e,
	0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x0a, 0x69, 0x6d, 0x70, 0x6f,
	0x72, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x3f, 0x0a, 0x0d, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0c, 0x72, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x65, 0x64, 0x41, 0x74, 0x12, 0x4f, 0x0a, 0x18, 0x73, 0x65, 0x72, 0x61, 0x63,
	0x68, 0x54, 0x79, 0x70, 0x65, 0x46, 0x6f, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x64, 0x41, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x42, 0x79, 0x52, 0x18,
	0x73, 0x65, 0x72, 0x61, 0x63, 0x68, 0x54, 0x79, 0x70, 0x65, 0x46, 0x6f, 0x72, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x64, 0x41, 0x74, 0x12, 0x36, 0x0a, 0x08, 0x64, 0x65, 0x61, 0x64,
	0x6c, 0x69, 0x6e, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x64, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65,
	0x12, 0x49, 0x0a, 0x15, 0x73, 0x65, 0x72, 0x61, 0x63, 0x68, 0x54, 0x79, 0x70, 0x65, 0x46, 0x6f,
	0x72, 0x44, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x13, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x43, 0x6f, 0x6d, 0x70, 0x61,
	0x72, 0x65, 0x42, 0x79, 0x52, 0x15, 0x73, 0x65, 0x72, 0x61, 0x63, 0x68, 0x54, 0x79, 0x70, 0x65,
	0x46, 0x6f, 0x72, 0x44, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x4b, 0x0a, 0x16, 0x73, 0x65, 0x72, 0x61, 0x63, 0x68,
	0x54, 0x79, 0x70, 0x65, 0x46, 0x6f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x42, 0x79, 0x52, 0x16, 0x73, 0x65, 0x72,
	0x61, 0x63, 0x68, 0x54, 0x79, 0x70, 0x65, 0x46, 0x6f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x22, 0xfe, 0x01, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61,
	0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x42, 0x0a, 0x0a,
	0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x22, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x52, 0x0a, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x12, 0x36, 0x0a, 0x08, 0x64, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08,
	0x64, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x22, 0x3a, 0x0a, 0x0a, 0x49, 0x6d, 0x70, 0x6f,
	0x72, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x45, 0x44, 0x49, 0x55, 0x4d,
	0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x56, 0x45, 0x52, 0x59, 0x5f, 0x48, 0x49, 0x47, 0x48, 0x10,
	0x01, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x49, 0x47, 0x48, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x4c,
	0x4f, 0x57, 0x10, 0x03, 0x22, 0xbb, 0x01, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54,
	0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x2b, 0x0a,
	0x0a, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0b, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x0a,
	0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x36, 0x0a, 0x08, 0x64, 0x65,
	0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x64, 0x65, 0x61, 0x64, 0x6c, 0x69,
	0x6e, 0x65, 0x22, 0x28, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x2a, 0x3a, 0x0a, 0x0a,
	0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x45,
	0x44, 0x49, 0x55, 0x4d, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x56, 0x45, 0x52, 0x59, 0x5f, 0x48,
	0x49, 0x47, 0x48, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x49, 0x47, 0x48, 0x10, 0x02, 0x12,
	0x07, 0x0a, 0x03, 0x4c, 0x4f, 0x57, 0x10, 0x03, 0x2a, 0x35, 0x0a, 0x12, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x42, 0x79, 0x12, 0x08,
	0x0a, 0x04, 0x53, 0x41, 0x4d, 0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x42, 0x45, 0x46, 0x4f,
	0x52, 0x45, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x46, 0x54, 0x45, 0x52, 0x10, 0x02, 0x32,
	0x35, 0x0a, 0x03, 0x43, 0x61, 0x74, 0x12, 0x2e, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x4d, 0x79, 0x43,
	0x61, 0x74, 0x12, 0x10, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x79, 0x43, 0x61, 0x74, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x1a, 0x0e, 0x2e, 0x4d, 0x79, 0x43, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0xc4, 0x02, 0x0a, 0x0b, 0x54, 0x61, 0x73, 0x6b, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2f, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x54, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x06, 0x2e,
	0x54, 0x61, 0x73, 0x6b, 0x73, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x54, 0x61,
	0x73, 0x6b, 0x73, 0x12, 0x1f, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x42, 0x79, 0x43,
	0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x1a, 0x06, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x22, 0x00, 0x12, 0x2c,
	0x0a, 0x07, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x18, 0x2e, 0x47, 0x65, 0x74, 0x54,
	0x61, 0x73, 0x6b, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x1a, 0x05, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x0a,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x17, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x1a, 0x05, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x0a,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x17, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x1a, 0x05, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x0a,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x17, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x23, 0x5a,
	0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x54, 0x69, 0x72, 0x61,
	0x74, 0x6f, 0x6d, 0x2f, 0x67, 0x69, 0x6e, 0x2d, 0x73, 0x74, 0x75, 0x64, 0x79, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gRPC_gin_study_proto_rawDescOnce sync.Once
	file_gRPC_gin_study_proto_rawDescData = file_gRPC_gin_study_proto_rawDesc
)

func file_gRPC_gin_study_proto_rawDescGZIP() []byte {
	file_gRPC_gin_study_proto_rawDescOnce.Do(func() {
		file_gRPC_gin_study_proto_rawDescData = protoimpl.X.CompressGZIP(file_gRPC_gin_study_proto_rawDescData)
	})
	return file_gRPC_gin_study_proto_rawDescData
}

var file_gRPC_gin_study_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_gRPC_gin_study_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_gRPC_gin_study_proto_goTypes = []interface{}{
	(Importance)(0),                        // 0: Importance
	(TimestampCompareBy)(0),                // 1: TimestampCompareBy
	(CreateTaskRequestParam_Importance)(0), // 2: CreateTaskRequestParam.Importance
	(*GetMyCatMessage)(nil),                // 3: GetMyCatMessage
	(*MyCatResponse)(nil),                  // 4: MyCatResponse
	(*Task)(nil),                           // 5: Task
	(*Tasks)(nil),                          // 6: Tasks
	(*GetTaskByIdRequestParam)(nil),        // 7: GetTaskByIdRequestParam
	(*GetTaskByConditionRequestParam)(nil), // 8: GetTaskByConditionRequestParam
	(*CreateTaskRequestParam)(nil),         // 9: CreateTaskRequestParam
	(*UpdateTaskRequestParam)(nil),         // 10: UpdateTaskRequestParam
	(*DeleteTaskRequestParam)(nil),         // 11: DeleteTaskRequestParam
	(*timestamppb.Timestamp)(nil),          // 12: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                  // 13: google.protobuf.Empty
}
var file_gRPC_gin_study_proto_depIdxs = []int32{
	0,  // 0: Task.importance:type_name -> Importance
	12, // 1: Task.registered_at:type_name -> google.protobuf.Timestamp
	12, // 2: Task.deadline:type_name -> google.protobuf.Timestamp
	12, // 3: Task.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 4: Tasks.tasks:type_name -> Task
	0,  // 5: GetTaskByConditionRequestParam.importance:type_name -> Importance
	12, // 6: GetTaskByConditionRequestParam.registered_at:type_name -> google.protobuf.Timestamp
	1,  // 7: GetTaskByConditionRequestParam.serachTypeForRegisterdAt:type_name -> TimestampCompareBy
	12, // 8: GetTaskByConditionRequestParam.deadline:type_name -> google.protobuf.Timestamp
	1,  // 9: GetTaskByConditionRequestParam.serachTypeForDeadline:type_name -> TimestampCompareBy
	12, // 10: GetTaskByConditionRequestParam.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 11: GetTaskByConditionRequestParam.serachTypeForUpdatedAt:type_name -> TimestampCompareBy
	2,  // 12: CreateTaskRequestParam.importance:type_name -> CreateTaskRequestParam.Importance
	12, // 13: CreateTaskRequestParam.deadline:type_name -> google.protobuf.Timestamp
	0,  // 14: UpdateTaskRequestParam.importance:type_name -> Importance
	12, // 15: UpdateTaskRequestParam.deadline:type_name -> google.protobuf.Timestamp
	3,  // 16: Cat.GetMyCat:input_type -> GetMyCatMessage
	13, // 17: TaskService.GetAllTasks:input_type -> google.protobuf.Empty
	8,  // 18: TaskService.GetTasks:input_type -> GetTaskByConditionRequestParam
	7,  // 19: TaskService.GetTask:input_type -> GetTaskByIdRequestParam
	9,  // 20: TaskService.CreateTask:input_type -> CreateTaskRequestParam
	10, // 21: TaskService.UpdateTask:input_type -> UpdateTaskRequestParam
	11, // 22: TaskService.DeleteTask:input_type -> DeleteTaskRequestParam
	4,  // 23: Cat.GetMyCat:output_type -> MyCatResponse
	6,  // 24: TaskService.GetAllTasks:output_type -> Tasks
	6,  // 25: TaskService.GetTasks:output_type -> Tasks
	5,  // 26: TaskService.GetTask:output_type -> Task
	5,  // 27: TaskService.CreateTask:output_type -> Task
	5,  // 28: TaskService.UpdateTask:output_type -> Task
	13, // 29: TaskService.DeleteTask:output_type -> google.protobuf.Empty
	23, // [23:30] is the sub-list for method output_type
	16, // [16:23] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_gRPC_gin_study_proto_init() }
func file_gRPC_gin_study_proto_init() {
	if File_gRPC_gin_study_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gRPC_gin_study_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMyCatMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gRPC_gin_study_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyCatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gRPC_gin_study_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gRPC_gin_study_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tasks); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gRPC_gin_study_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTaskByIdRequestParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gRPC_gin_study_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTaskByConditionRequestParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gRPC_gin_study_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTaskRequestParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gRPC_gin_study_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTaskRequestParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gRPC_gin_study_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTaskRequestParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gRPC_gin_study_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_gRPC_gin_study_proto_goTypes,
		DependencyIndexes: file_gRPC_gin_study_proto_depIdxs,
		EnumInfos:         file_gRPC_gin_study_proto_enumTypes,
		MessageInfos:      file_gRPC_gin_study_proto_msgTypes,
	}.Build()
	File_gRPC_gin_study_proto = out.File
	file_gRPC_gin_study_proto_rawDesc = nil
	file_gRPC_gin_study_proto_goTypes = nil
	file_gRPC_gin_study_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CatClient is the client API for Cat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CatClient interface {
	GetMyCat(ctx context.Context, in *GetMyCatMessage, opts ...grpc.CallOption) (*MyCatResponse, error)
}

type catClient struct {
	cc grpc.ClientConnInterface
}

func NewCatClient(cc grpc.ClientConnInterface) CatClient {
	return &catClient{cc}
}

func (c *catClient) GetMyCat(ctx context.Context, in *GetMyCatMessage, opts ...grpc.CallOption) (*MyCatResponse, error) {
	out := new(MyCatResponse)
	err := c.cc.Invoke(ctx, "/Cat/GetMyCat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatServer is the server API for Cat service.
type CatServer interface {
	GetMyCat(context.Context, *GetMyCatMessage) (*MyCatResponse, error)
}

// UnimplementedCatServer can be embedded to have forward compatible implementations.
type UnimplementedCatServer struct {
}

func (*UnimplementedCatServer) GetMyCat(context.Context, *GetMyCatMessage) (*MyCatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMyCat not implemented")
}

func RegisterCatServer(s *grpc.Server, srv CatServer) {
	s.RegisterService(&_Cat_serviceDesc, srv)
}

func _Cat_GetMyCat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyCatMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServer).GetMyCat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Cat/GetMyCat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServer).GetMyCat(ctx, req.(*GetMyCatMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Cat_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Cat",
	HandlerType: (*CatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMyCat",
			Handler:    _Cat_GetMyCat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gRPC/gin-study.proto",
}

// TaskServiceClient is the client API for TaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TaskServiceClient interface {
	//
	//全タスクの取得
	GetAllTasks(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Tasks, error)
	//
	//条件付きタスクの取得
	GetTasks(ctx context.Context, in *GetTaskByConditionRequestParam, opts ...grpc.CallOption) (*Tasks, error)
	//
	//id指定でタスクの取得
	//・エラー返却について
	//- NotFound：idに対応するタスクが存在しない
	//- InvalidArgument：引数の内容が不適切
	GetTask(ctx context.Context, in *GetTaskByIdRequestParam, opts ...grpc.CallOption) (*Task, error)
	// タスクの新規作成
	//・エラー返却について
	//- InvalidArgument：引数の内容が不適切
	CreateTask(ctx context.Context, in *CreateTaskRequestParam, opts ...grpc.CallOption) (*Task, error)
	// タスクの更新
	//・エラー返却について
	//- NotFound：idに対応するタスクが存在しない
	//- InvalidArgument：引数の内容が不適切
	UpdateTask(ctx context.Context, in *UpdateTaskRequestParam, opts ...grpc.CallOption) (*Task, error)
	// タスクの一件削除
	//・エラー返却について
	//- NotFound：idに対応するタスクが存在しない
	//- InvalidArgument：引数の内容が不適切
	DeleteTask(ctx context.Context, in *DeleteTaskRequestParam, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type taskServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskServiceClient(cc grpc.ClientConnInterface) TaskServiceClient {
	return &taskServiceClient{cc}
}

func (c *taskServiceClient) GetAllTasks(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Tasks, error) {
	out := new(Tasks)
	err := c.cc.Invoke(ctx, "/TaskService/GetAllTasks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetTasks(ctx context.Context, in *GetTaskByConditionRequestParam, opts ...grpc.CallOption) (*Tasks, error) {
	out := new(Tasks)
	err := c.cc.Invoke(ctx, "/TaskService/GetTasks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetTask(ctx context.Context, in *GetTaskByIdRequestParam, opts ...grpc.CallOption) (*Task, error) {
	out := new(Task)
	err := c.cc.Invoke(ctx, "/TaskService/GetTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) CreateTask(ctx context.Context, in *CreateTaskRequestParam, opts ...grpc.CallOption) (*Task, error) {
	out := new(Task)
	err := c.cc.Invoke(ctx, "/TaskService/CreateTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) UpdateTask(ctx context.Context, in *UpdateTaskRequestParam, opts ...grpc.CallOption) (*Task, error) {
	out := new(Task)
	err := c.cc.Invoke(ctx, "/TaskService/UpdateTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) DeleteTask(ctx context.Context, in *DeleteTaskRequestParam, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/TaskService/DeleteTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskServiceServer is the server API for TaskService service.
type TaskServiceServer interface {
	//
	//全タスクの取得
	GetAllTasks(context.Context, *emptypb.Empty) (*Tasks, error)
	//
	//条件付きタスクの取得
	GetTasks(context.Context, *GetTaskByConditionRequestParam) (*Tasks, error)
	//
	//id指定でタスクの取得
	//・エラー返却について
	//- NotFound：idに対応するタスクが存在しない
	//- InvalidArgument：引数の内容が不適切
	GetTask(context.Context, *GetTaskByIdRequestParam) (*Task, error)
	// タスクの新規作成
	//・エラー返却について
	//- InvalidArgument：引数の内容が不適切
	CreateTask(context.Context, *CreateTaskRequestParam) (*Task, error)
	// タスクの更新
	//・エラー返却について
	//- NotFound：idに対応するタスクが存在しない
	//- InvalidArgument：引数の内容が不適切
	UpdateTask(context.Context, *UpdateTaskRequestParam) (*Task, error)
	// タスクの一件削除
	//・エラー返却について
	//- NotFound：idに対応するタスクが存在しない
	//- InvalidArgument：引数の内容が不適切
	DeleteTask(context.Context, *DeleteTaskRequestParam) (*emptypb.Empty, error)
}

// UnimplementedTaskServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTaskServiceServer struct {
}

func (*UnimplementedTaskServiceServer) GetAllTasks(context.Context, *emptypb.Empty) (*Tasks, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllTasks not implemented")
}
func (*UnimplementedTaskServiceServer) GetTasks(context.Context, *GetTaskByConditionRequestParam) (*Tasks, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTasks not implemented")
}
func (*UnimplementedTaskServiceServer) GetTask(context.Context, *GetTaskByIdRequestParam) (*Task, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTask not implemented")
}
func (*UnimplementedTaskServiceServer) CreateTask(context.Context, *CreateTaskRequestParam) (*Task, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTask not implemented")
}
func (*UnimplementedTaskServiceServer) UpdateTask(context.Context, *UpdateTaskRequestParam) (*Task, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTask not implemented")
}
func (*UnimplementedTaskServiceServer) DeleteTask(context.Context, *DeleteTaskRequestParam) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTask not implemented")
}

func RegisterTaskServiceServer(s *grpc.Server, srv TaskServiceServer) {
	s.RegisterService(&_TaskService_serviceDesc, srv)
}

func _TaskService_GetAllTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetAllTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TaskService/GetAllTasks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetAllTasks(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskByConditionRequestParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TaskService/GetTasks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetTasks(ctx, req.(*GetTaskByConditionRequestParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskByIdRequestParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TaskService/GetTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetTask(ctx, req.(*GetTaskByIdRequestParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskRequestParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TaskService/CreateTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).CreateTask(ctx, req.(*CreateTaskRequestParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_UpdateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTaskRequestParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).UpdateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TaskService/UpdateTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).UpdateTask(ctx, req.(*UpdateTaskRequestParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_DeleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTaskRequestParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).DeleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TaskService/DeleteTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).DeleteTask(ctx, req.(*DeleteTaskRequestParam))
	}
	return interceptor(ctx, in, info, handler)
}

var _TaskService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "TaskService",
	HandlerType: (*TaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllTasks",
			Handler:    _TaskService_GetAllTasks_Handler,
		},
		{
			MethodName: "GetTasks",
			Handler:    _TaskService_GetTasks_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _TaskService_GetTask_Handler,
		},
		{
			MethodName: "CreateTask",
			Handler:    _TaskService_CreateTask_Handler,
		},
		{
			MethodName: "UpdateTask",
			Handler:    _TaskService_UpdateTask_Handler,
		},
		{
			MethodName: "DeleteTask",
			Handler:    _TaskService_DeleteTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gRPC/gin-study.proto",
}
