// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: gin-study.proto

package grpc

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *GetMyCatMessage) Validate() error {
	return nil
}
func (this *MyCatResponse) Validate() error {
	return nil
}
func (this *Task) Validate() error {
	if this.RegisteredAt != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.RegisteredAt); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("RegisteredAt", err)
		}
	}
	if this.Deadline != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Deadline); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Deadline", err)
		}
	}
	if this.UpdatedAt != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.UpdatedAt); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("UpdatedAt", err)
		}
	}
	return nil
}
func (this *Tasks) Validate() error {
	for _, item := range this.Tasks {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Tasks", err)
			}
		}
	}
	return nil
}
func (this *GetTaskByIdRequestParam) Validate() error {
	return nil
}
func (this *GetTaskByConditionRequestParam) Validate() error {
	if this.RegisteredAt != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.RegisteredAt); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("RegisteredAt", err)
		}
	}
	if this.Deadline != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Deadline); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Deadline", err)
		}
	}
	if this.UpdatedAt != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.UpdatedAt); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("UpdatedAt", err)
		}
	}
	return nil
}
func (this *CreateTaskRequestParam) Validate() error {
	if !(len(this.Name) > 1) {
		return github_com_mwitkow_go_proto_validators.FieldError("Name", fmt.Errorf(`value '%v' must have a length greater than '1'`, this.Name))
	}
	if !(len(this.Details) > 1) {
		return github_com_mwitkow_go_proto_validators.FieldError("Details", fmt.Errorf(`value '%v' must have a length greater than '1'`, this.Details))
	}
	if !(len(this.ImportanceName) > 1) {
		return github_com_mwitkow_go_proto_validators.FieldError("ImportanceName", fmt.Errorf(`value '%v' must have a length greater than '1'`, this.ImportanceName))
	}
	if nil == this.Deadline {
		return github_com_mwitkow_go_proto_validators.FieldError("Deadline", fmt.Errorf("message must exist"))
	}
	if this.Deadline != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Deadline); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Deadline", err)
		}
	}
	return nil
}
func (this *UpdateTaskRequestParam) Validate() error {
	if this.Deadline != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Deadline); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Deadline", err)
		}
	}
	return nil
}
func (this *DeleteTaskRequestParam) Validate() error {
	return nil
}
func (this *Importance) Validate() error {
	return nil
}
