name: ci
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.0.26
        ports:
          - 13306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: gin_study
          MYSQL_USER: docker
          MYSQL_PASSWORD: docker
          TZ: "Asia/Tokyo"
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.4
        with:
          go-version: '1.16'
      - run: go version
  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: latest
  test:
    # needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.4
        with:
          go-version: '1.16'
      - run: go version
      - uses: actions/checkout@v2
      - name: build test
        run: go build
      - name: test
        run: go test ./infrastructure/repository_impl/...
        # run: go test ./... -v
